apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "hello-sql.fullname" . }}
  labels:
    app: {{ include "hello-sql.name" . }}
    chart: {{ include "hello-sql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-sql.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "hello-sql.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.helloSQL.listening_port }}
              protocol: TCP
          env:
          - name: LISTENING_PORT
            value: {{ .Values.helloSQL.listening_port | quote }}
          - name: DB_USER
            value: {{ .Values.helloSQL.db_user | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.helloSQL.db_password | quote }}
          - name: DB_HOST
            value: "{{ template "hello-sql.mysql.fullname" . }}"
          - name: DB_PORT
            value: {{ .Values.helloSQL.db_port | quote }}
          - name: DB_NAME
            value: {{ .Values.helloSQL.db_name | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
