apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-sql-mysql
  labels:
    app: hello-sql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-sql
      tier: database
  template:
    metadata:
      labels:
        app: hello-sql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: "homer"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "mysite"
