        image: mysql/mysql-server:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: "homer"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "mysite"
